version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  murmur-rest:
#   image: alfg/murmur-rest
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_DEBUG=True
      - APP_SECRET_KEY=supersecret
      - MURMUR_ICE_HOST=murmurd
      - MURMUR_ICE_PORT=6502
      - ENABLE_AUTH=True
      - USERS=admin:password,admin2:password2
      - VIRTUAL_HOST=localhost
    ports:
      - "8080:8080"
    #   - "5000:5000"
    links:
      - "murmurd"
    # volumes:
    #   - "./:/opt/murmur-rest"

  murmurd:
    image: alfg/murmur
    ports:
      - "127.0.0.1:6502:6502"
      - "50000-50050:50000-50050"
      - "50000-50050:50000-50050/udp"
    volumes:
      - ./etc/murmur.ini:/etc/murmur/murmur.ini
      - murmurdb:/var/lib/murmur/

volumes:
  murmurdb: